# Define variables
SRC_DIR := .
TXT_FILES := $(wildcard $(SRC_DIR)/*.txt)
XLSX_FILES := $(wildcard $(SRC_DIR)/*.xlsx)

# Define targets
.PHONY: all clean

all: build install configure

build:
	@echo "TO-DO Building..."

install:
	@echo "TO-DO Installing..."

configure:
	@echo "TO-DO Configuring..."

clean:
	@echo "Cleaning..."
	rm -f $(TXT_FILES) $(XLSX_FILES)
